# Generated by Django 3.2 on 2022-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=100)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_Password', models.CharField(max_length=100)),
                ('seller_status', models.CharField(default='active', max_length=100)),
            ],
        ),
    ]
