# Generated by Django 3.2 on 2022-01-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft_seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccountdetails',
            old_name='seller_username',
            new_name='seller_mobile_no',
        ),
    ]
