# Generated by Django 3.2 on 2022-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft_seller', '0002_rename_seller_username_selleraccountdetails_seller_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccountdetails',
            name='seller_status',
            field=models.CharField(default='deactive', max_length=100),
        ),
    ]
