# Generated by Django 3.2 on 2022-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft_seller', '0003_alter_selleraccountdetails_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccountdetails',
            name='seller_status',
            field=models.CharField(default='deactivate', max_length=100),
        ),
    ]
