# Generated by Django 3.2 on 2022-02-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft_seller', '0004_alter_selleraccountdetails_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishName', models.CharField(max_length=100)),
                ('fishCatogory', models.CharField(default='deactivate', max_length=100)),
                ('fishPrice', models.IntegerField()),
                ('fishDiscountPrice', models.IntegerField()),
                ('fishColor', models.CharField(default='deactivate', max_length=100)),
                ('fishQuantity', models.IntegerField()),
                ('fishDescription', models.CharField(max_length=100)),
                ('fishImage', models.CharField(default='deactivate', max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craft_seller.selleraccountdetails')),
            ],
        ),
    ]
