# Generated by Django 3.2 on 2022-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0002_auto_20211011_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
