# Generated by Django 3.2 on 2022-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0003_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='deactive', max_length=100),
        ),
    ]
