# Generated by Django 3.2 on 2022-02-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0004_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=100)),
                ('fish_catogory', models.CharField(max_length=100)),
                ('fish_price', models.IntegerField()),
                ('fish_discount_price', models.IntegerField()),
                ('fish_color', models.CharField(max_length=100)),
                ('fish_description', models.TextField()),
                ('fish_image', models.CharField(max_length=100)),
                ('whishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craft.user')),
            ],
        ),
    ]
