# Generated by Django 3.2 on 2022-02-27 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0008_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
