# Generated by Django 3.2 on 2022-03-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0014_auto_20220309_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='p_quantity',
        ),
    ]
